<a href="https://colab.research.google.com/github/saided/pandas_using_python/blob/master/np.where.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#np.where

In [0]:
import numpy as np
arr = np.arange(10,20)
a = np.where(arr<15) # np.where returns an array of position where the given condition is satisfied in the array

In [9]:
a[0] # If you know that it is one-dimensional, you can use the first element of the result of np.where() as it is

array([0, 1, 2, 3, 4])

In [0]:
#Using numpy.where(), elements of the NumPy array ndarray that satisfy the conditions can be replaced or performed specified processing.
#numpy.where(condition[, x, y])
#Return elements, either from x or y, depending on condition.
#If only condition is given, return condition.nonzero()
#np.where() is a function that returns ndarray which is x if condition is True and y if False. x, y and condition need to be broadcastable to same shape.
#If x andy are omitted, index is returned. As shown in the above example.

In [10]:
a = np.arange(9).reshape((3, 3))
print(np.where(a < 4, -1, 100)) # elements 0,1,2,3 will be replaced with -1(as they satisfy the given condition) and 4 to 8 are replaced with 100 in the resulting array


[[ -1  -1  -1]
 [ -1 100 100]
 [100 100 100]]


In [11]:
#We can also ise multiple conditions
print(np.where((a > 2) & (a < 6), -1, 100)) # here 3,4,5 will be replaced with -1 and the rest with 100

[[100 100 100]
 [ -1  -1  -1]
 [100 100 100]]


In [12]:
print(np.where((a > 2) & (a < 6) | (a == 7), -1, 100))


[[100 100 100]
 [ -1  -1  -1]
 [100  -1 100]]


In [17]:
# It is also possible to replace elements with an arbitrary value only when the condition is satisfied or only when the condition is not satisfied
print(np.where(a < 4, -1, a))
print('*************')
print(np.where(a < 4, a, 100))


[[-1 -1 -1]
 [-1  4  5]
 [ 6  7  8]]
*************
[[  0   1   2]
 [  3 100 100]
 [100 100 100]]


In [18]:
a_org = np.arange(9).reshape((3, 3))
print(a_org)
a_new = np.where(a_org < 4, -1, a_org)
print(a_new)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-1 -1 -1]
 [-1  4  5]
 [ 6  7  8]]


In [20]:
# Note that np.where() returns a new ndarray, and the original ndarray is unchanged
print(a_org)
# if we want to change the original array itself then
a_org[a_org < 4] = -1
print(a_org)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-1 -1 -1]
 [-1  4  5]
 [ 6  7  8]]


In [24]:
# Process the elements that satisfy the condition
a = np.arange(10,19).reshape(3,3)
print(a)
b = np.where(a<15,a**2,a) # 10 to 14 will be squared and the remaining will be as it is
print(b)
print(a) # Here again the original array remains same

[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[100 121 144]
 [169 196  15]
 [ 16  17  18]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [25]:
a = np.array([3,6,9,12,15])
b = np.array([2,4,6,8,12])
c = np.where(a == b)
print(c[0]) # for one dimensional array first index will return the array

[]


In [26]:
a = np.array([1.0,2.2,3.5])
a = a/0.0
print(a[0])

inf


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [28]:
a = np.array([1,2,3,4])
print(a.dtype)
a[0] =0.9
print(a[0], a.dtype)

int64
0 int64


In [29]:
a = np.array([[1,2,3,], [4,5,6]])
print(a[1][2])

6
