<a href="https://colab.research.google.com/github/saided/pandas_using_python/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Operations

In [1]:
import numpy as np
arr1 = np.random.rand(3,4)
arr1

array([[0.55124129, 0.9454753 , 0.42595002, 0.92078581],
       [0.89218564, 0.69824831, 0.7931436 , 0.38237646],
       [0.49673032, 0.04387624, 0.48543234, 0.76772473]])

In [2]:
arr2 = np.random.rand(3,4)
arr2

array([[0.09465971, 0.86762568, 0.35535573, 0.54249633],
       [0.57387556, 0.54806672, 0.36300721, 0.10622178],
       [0.85616826, 0.02741867, 0.68994983, 0.11959782]])

In [3]:
arr1+arr2

array([[0.64590101, 1.81310098, 0.78130575, 1.46328214],
       [1.4660612 , 1.24631503, 1.15615081, 0.48859823],
       [1.35289858, 0.07129491, 1.17538217, 0.88732256]])

In [4]:
arr1-arr2

array([[ 0.45658158,  0.07784962,  0.0705943 ,  0.37828948],
       [ 0.31831007,  0.15018159,  0.43013639,  0.27615468],
       [-0.35943794,  0.01645757, -0.20451749,  0.64812691]])

In [5]:
arr1/arr2


array([[5.82339915, 1.08972719, 1.19865811, 1.69731251],
       [1.55466741, 1.27402063, 2.1849252 , 3.59979336],
       [0.58017838, 1.6002324 , 0.70357629, 6.41922004]])

In [6]:
arr1*arr2 # it does point to point multiplication

array([[0.05218034, 0.82031865, 0.15136378, 0.49952292],
       [0.51200353, 0.38268666, 0.28791684, 0.04061671],
       [0.42528473, 0.00120303, 0.33492396, 0.09181821]])

In [40]:
arr3 = np.random.rand(100000,2)
arr3
# So here we can assume that col1 represents x co-ordintes and col2 represents y co-ordinates
# radius of the circle is 1
# Now for any ponint to lie insid ethe circle the dist from center of the circle to that point should be less than the radius of the circle
# Here center is (0,0) and radius is given as 1
# So dist formula will besimply sqrt(X*2 + Y*2)

array([[0.83035966, 0.15462394],
       [0.81140481, 0.05948856],
       [0.37495173, 0.87829873],
       ...,
       [0.66976688, 0.07572963],
       [0.72419092, 0.40113153],
       [0.35047472, 0.53189672]])

In [41]:
arr4 = (arr3**2)
arr4

array([[0.68949717, 0.02390856],
       [0.65837777, 0.00353889],
       [0.1405888 , 0.77140867],
       ...,
       [0.44858767, 0.00573498],
       [0.52445249, 0.1609065 ],
       [0.12283253, 0.28291412]])

In [42]:
arr4[:,0]

array([0.68949717, 0.65837777, 0.1405888 , ..., 0.44858767, 0.52445249,
       0.12283253])

In [43]:
arr4[:,1]

array([0.02390856, 0.00353889, 0.77140867, ..., 0.00573498, 0.1609065 ,
       0.28291412])

In [0]:
arr5 = arr4[:,0]+arr4[:,1]

In [47]:
arr6 =np.sqrt(arr5)
count= 0 
#arr6<1.0
for i in range(len(arr6)):
  if arr6[i]>1:
    count+=1
print(count/100000)

0.21415


In [49]:
a = np.random.rand(5,2)
a

array([[0.01038869, 0.11913658],
       [0.60687985, 0.40911438],
       [0.13279808, 0.97762485],
       [0.44515913, 0.71453266],
       [0.02743487, 0.25256809]])

In [54]:
s = np.sum(a,axis=1) # it performs sum along the columns and the resulting matrix size is (R x 1)
s1 = np.sum(a,axis=0) # it performs the sum along the rows and the resulting matrix size is (1 x C)
s>1 # three elements are greater then 1 but it prints only the boolean matrix
# to return the actual count of elements that are greater than 1 we use this
np.sum(s>1)



3

In [60]:
ndim = 2
npoints = 100000
points = np.random.rand(npoints,ndim)
points_sq = points**2
points_sum = np.sum(points_sq,axis=1)
points_sum # x*2 +y*2
dist = np.sqrt(points_sum)
outside_points = np.sum(dist>1)
outside_points
print('Fraction of points lying outside the circle :', outside_points/npoints)


Fraction of points lying outside the circle : 0.21333


# Broadcasting


In [1]:
import numpy as np
arr1 = np.arange(6).reshape((3,2))
arr2 = np.arange(6).reshape((3,2))
#Broadcasting is possible as they are of same dimensions
arr1+arr2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [6]:
arr1 + arr2[2].reshape((1,2)) #(3,2) + (1,2) Broadcasting possible as 1 can be extended to 3

array([[ 4,  6],
       [ 6,  8],
       [ 8, 10]])

In [11]:
arr1 + arr2[:,0].reshape((3,1)) #(3,2) + (3,1) broadcasting possible as 1 can be extended to 2


array([[0, 1],
       [4, 5],
       [8, 9]])

In [12]:
arr1 = np.random.rand(24).reshape(2,3,4)
arr1

array([[[0.34279647, 0.22790303, 0.3470957 , 0.10620698],
        [0.68459099, 0.15478131, 0.69396406, 0.97031119],
        [0.07943105, 0.86664536, 0.53476856, 0.39730905]],

       [[0.06452253, 0.30430088, 0.4174702 , 0.90668737],
        [0.24041022, 0.65967214, 0.19493149, 0.25358325],
        [0.57974353, 0.75638814, 0.08447547, 0.523454  ]]])

In [0]:
arr2 = np.ones((1,4))

In [15]:
arr1+arr2 #(2,3,4)+(1,4) broadcasting is possible as 1 can be extended to 3 and 2 can be replicated to empty

array([[[1.34279647, 1.22790303, 1.3470957 , 1.10620698],
        [1.68459099, 1.15478131, 1.69396406, 1.97031119],
        [1.07943105, 1.86664536, 1.53476856, 1.39730905]],

       [[1.06452253, 1.30430088, 1.4174702 , 1.90668737],
        [1.24041022, 1.65967214, 1.19493149, 1.25358325],
        [1.57974353, 1.75638814, 1.08447547, 1.523454  ]]])

# File handling with Numpy

In [3]:
import numpy as np
planets_small = np.loadtxt('planets_small.txt')

ValueError: ignored

In [4]:
#here the above code cannot convert MERCURY as it is a string
#so we have to skip that row which contains the planets names
planets_small = np.loadtxt('planets_small.txt',skiprows=1) # it skips the first row


ValueError: ignored

In [0]:
# but still the index contains string parameters
# so we have to also skip that column and use only that columns which we want to use
# so we will mention the columns we wnt to us ein usecols block
planets_small = np.loadtxt('planets_small.txt',skiprows=1,usecols=[1,2,3,4,5,6,7,8,9])


In [11]:
planets_small

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

In [12]:
planets_large = np.loadtxt('planets_large.txt',skiprows=1,usecols=[1,2,3,4,5,6,7,8,9])

ValueError: ignored

In [13]:
# The problem with the above code is that there are some filed whose value is Unknown 
# So to avoid this we use generate from text
planets_large = np.genfromtxt('planets_large.txt',skip_header=1,usecols=[1,2,3,4,5,6,7,8,9]) # skip_header in place of skip_rows
planets_large

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [14]:
# here in the above data we can see that Unknown value is replaced with nan value
np.isnan(planets_large)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

In [16]:
# replace nan with some value foer ex -1
planets_new = np.nan_to_num(planets_large,nan=-1)
planets_new

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [18]:
# in the above code we replaced nan with -1 value
# now we will save the file
np.savetxt('planets_new.txt',planets_new,delimiter=',')
planets_new.shape

(20, 9)