<a href="https://colab.research.google.com/github/saided/pandas_using_python/blob/master/Stats_with_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#stats with Numpy

In [1]:
import numpy as np
arr = np.random.rand(100000,)
np.amin(arr)

1.186770073835497e-05

In [2]:
np.amax(arr)

0.9999651649404268

In [3]:
# To calculate the variance
np.var(arr)

0.08317257167423955

In [4]:
#TO calculate the standard deviation
np.std(arr)

0.28839655281268456

In [5]:
# to calculate the mean
np.mean(arr)

0.4994583449865205

In [6]:
# to claculate the Median
np.median(arr)

0.4993635938064149

In [7]:
# to calculate the percentiles
# 50th percentile
np.percentile(arr ,50) # it will be close to the median

0.4993635938064149

In [10]:
# to calculate 10th and 90th percentiles
np.percentile(arr,10)
np.percentile(arr,90)


0.8984966350836462

In [11]:
# to calculate IQR ie 75th percentile - 25th percentile
IQR = np.percentile(arr,75) - np.percentile(arr,25)
IQR

0.4999628218694028

In [12]:
quartiles  = np.percentile(arr,[25,50,75,100]) # we can give a list of percentiles that are to be calculated
quartiles

array([0.24901588, 0.49936359, 0.74897871, 0.99996516])

In [13]:
#now we can also IQR from  the above code.It requires less numpy calls
iqr = quartiles[2]-quartiles[0]
iqr

0.4999628218694028

In [15]:
# to calculate the z-score which tells us how far a data point is away from the mean in terms of std deviations
# z = (x - mean)/std
z_score = (arr - np.mean(arr))/np.std(arr)
z_score 

array([ 1.34239391, -0.12374952,  0.89150887, ..., -1.41894429,
       -1.05373948,  0.35302351])

In [16]:
# Numerical representation of histograms
np.histogram(arr)

(array([10044,  9996, 10024,  9950, 10052, 10030,  9910, 10042, 10095,
         9857]),
 array([1.18677007e-05, 1.00007197e-01, 2.00002527e-01, 2.99997857e-01,
        3.99993187e-01, 4.99988516e-01, 5.99983846e-01, 6.99979176e-01,
        7.99974505e-01, 8.99969835e-01, 9.99965165e-01]))

In [0]:
# in the above output we have two arrays
# First arrays represents the frequencies
# Second arrays represents the bin sizes. that is pos(0 to 1) reperesents one bin size and the first value in the first array represents its frequency


In [17]:
# we can also bins of our choice
np.histogram(arr,bins=5)
#pos(0-1) first bin
#pos(1-2) second bin
#pos(2-3) third bin
#pos(3-4) fourth bin
#pos(4-5) fifth bin

# As first array values represents the frequencies of the bins respectively

(array([20040, 19974, 20082, 19952, 19952]),
 array([1.18677007e-05, 2.00002527e-01, 3.99993187e-01, 5.99983846e-01,
        7.99974505e-01, 9.99965165e-01]))

In [18]:
# we can also give our own customized bins
np.histogram(arr,bins=[0,0.25,0.5,0.75,1]) # here we have created 4 bin intervals each of size equal to 0.25
# Accordingly we will get 4 frequency value sfor the respective bins in the first array

(array([25091, 24975, 25033, 24901]), array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [24]:
#we can also map points in the array to the respective bins
arr1 = np.random.randint(10,20,(10))
bins = [10,14,20]
arr1


array([16, 12, 11, 12, 11, 19, 17, 14, 13, 17])

In [25]:
np.histogram(arr1,bins)
# here we got that there are 5 values in each bins (10-14)and (14-20)
# here 14 is exclusive of the interval 10-14 it is inclusive in 14-20 interval

(array([5, 5]), array([10, 14, 20]))

In [26]:
#now to map values in the array to the bins
np.digitize(arr1,bins)

array([2, 1, 1, 1, 1, 2, 2, 2, 1, 2])

In [27]:
# in the above output 2 represents that the value at that point belongs to second bin(14-20) and 1 represents that the value belongs to the first bin(10-14)
bins1 = [0,5,10]
np.histogram(arr1,bins1)
# First array is zero as there are no values in the arr1 for the intervals 0-5 and 5-10

(array([0, 0]), array([ 0,  5, 10]))

In [37]:
arr2 = np.random.randint(50,100,(100))
arr3 =  np.random.randint(140,180,(100))
arr4 =  np.random.randint(19,25,(100))
# Now we want to merge all the arrays into ine for processing
np.concatenate((arr2,arr3,arr4)).shape

(300,)

In [0]:
# so concatenate just add elements under each which is not useful to us we need something like the array of type (3,4) 
#where each row belongs to arr2,arr3,arr4 respectively
# so for this we will use vstack and hstack

In [39]:
arr2d = np.vstack((arr2,arr3,arr4))
arr2d
#we will do Vstack if the columns are fixed for all the arrays

array([[ 52,  92,  79,  98,  58,  67,  61,  81,  79,  90,  96,  96,  81,
         60,  55,  56,  57,  80,  83,  80,  59,  73,  78,  54,  85,  70,
         53,  51,  91,  64,  69,  66,  56,  82,  75,  77,  58,  94,  53,
         58,  95,  58,  71,  94,  87,  93,  59,  86,  71,  64,  76,  50,
         63,  65,  72,  89,  81,  87,  90,  87,  79,  82,  69,  52,  55,
         60,  96,  64,  77,  62,  90,  57,  52,  95,  74,  72,  97,  65,
         90,  63,  61,  98,  58,  86,  89,  57,  57,  71,  96,  77,  83,
         63,  96,  73,  99,  71,  94,  70,  93,  78],
       [145, 164, 140, 167, 172, 175, 156, 160, 178, 169, 154, 166, 166,
        168, 167, 163, 149, 156, 174, 140, 140, 151, 161, 174, 178, 162,
        153, 160, 156, 177, 152, 155, 174, 148, 141, 142, 148, 149, 150,
        146, 163, 155, 176, 175, 159, 167, 156, 165, 165, 156, 160, 178,
        168, 177, 162, 144, 147, 153, 165, 160, 165, 165, 162, 170, 157,
        174, 140, 155, 153, 169, 147, 165, 171, 148, 144, 144, 175, 16

In [40]:
np.amin(arr2d,axis = 1) # it gives min value across the each row
# if we dont give axis=1 then it prints out the min value from the whole array

array([ 50, 140,  19])

In [41]:
np.mean(arr2d,axis=1)

array([ 74.26, 159.22,  21.33])

In [0]:
bins2 = [50,60,70,80,90,100]
bins3 = [140,150,160,170,180]
bins4 = [19,20,21,22,23,24,25]
